I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 121, in script
    K "*Kyle nudges Daniella with his elbow* That’s where we come in. We could change history with this movie…"
Exception: Sayer 'K' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 121, in script
    K "*Kyle nudges Daniella with his elbow* That’s where we come in. We could change history with this movie…"
  File "C:\Users\z0010\Downloads\renpy-8.0.1-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\z0010\Downloads\renpy-8.0.1-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'K' is not defined.

Windows-10-10.0.19042 AMD64
Ren'Py 8.0.1.22070801
project 1.0
Tue Aug 16 21:12:39 2022
