I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 23, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 23, in script
    e "You've created a new Ren'Py game."
  File "/Users/zhengz/Desktop/renpy-8.0.1-sdk/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/zhengz/Desktop/renpy-8.0.1-sdk/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.1.22070801
project 1.0
Mon Aug  8 15:21:56 2022
